### ISSUE TITLE
How to activate two kinds of env at the same time?

### ISSUE THREAD

**Issue by Magicloud** [denibertovic/denv#2]
For example, when using AWS EKS, I need both AWS envs and K8S config. `denv aws` then `denv kube` says "Env already active."

**Comment by denibertovic** [comment]
hey @Magicloud I initially designed this so that only ONE env can be activate at a time! The only exception to this rule was the AWS env which supports the so called "exec mode". So you would run `denv kube ...` first and then you can run the aws in exec mode like so: `denv aws -p ... -- /your/command/here`. 

I've played around with the idea of adding "exec mode" to all subcommands but haven't gotten around to it yet.

**Comment by Magicloud** [comment]
But exec mode is kind of ... unless "/your/command/here" is a new shell.

May be an env can contain a few confs, like "Prod" env contains both aws profile, and k8s profile?

**Comment by denibertovic** [comment]
@Magicloud I'm not sure I follow? You can use `/bin/bash - c "...." `. Does that not do what you need?

The recommended way for using aws env is exec form as to not have a along running shell with the secrets exposed. I use short lived credentials so it's important I don't end up with a shell with expired credentials.

**Comment by Magicloud** [comment]
I agree on the security consideration. I meant that exec mode leads to a long string typed every time, wondering if it can be shorten.

**Comment by denibertovic** [comment]
I agree. However I value explicit over implicit envs and in the case of the aws env it's valuable to type out the command each time given security considerations. I don't mind long commands since I usually only have to type it once and let my shell find it from it's history when I need it again. The other trick I use heavily is wrapping long commands into a Makefile (for example [here](https://github.com/denibertovic/makefiles/blob/master/terraform.makefile#L29).) 

Denv is currently heavily predicated on the idea of explicit vs implicit and separating different envs so I don't think I'm going to implement the possibility  to activate 2 or more envs at the same time. Other than the support with exec form that's already there. Sorry.

Sidenote: I will probably add exec form to all the other envs in the future.

If it's fine with you I'll close this issue. Please re-open if I left any question unaddressed.
